DELETE http://localhost:3001/MINKAN/api/chats/639fa4f446c98f01ab530213
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2MzlmNzJlMzJiYTAzNmRmYjZhOTZiMDkiLCJpYXQiOjE2NzE0MDcyMTksImV4cCI6MTY3MTQxMDgxOX0.SQzpvyo6LYNQPU6tf057D10CZ55k-kPGy_sFafhwLdY