DELETE http://localhost:3001/MINKAN/api/messages/639faf504a569cedcbcf8b35
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI2MzlmNDZjZGFjNGMwYTk1MDk1ZDYyM2EiLCJpYXQiOjE2NzE0MDk0NzUsImV4cCI6MTY3MTQxMzA3NX0.v1VuZYBzlIsJnJhCBOiHZ8BzdbUDseJWnsXLIRqsE8c