GET http://localhost:3001/MINKAN/api/chats/fromUser/63c5cf02581b40c85c0228aa/byUser/63c5cef1581b40c85c0228a3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWQiOiI2M2M1Y2YwMjU4MWI0MGM4NWMwMjI4YWEiLCJpYXQiOjE2NzQwOTgzNzIsImV4cCI6MTY3NDEwMTk3Mn0.P1Ei-2uLMseFe2ZzY_sbriewKRY-_piB8iC0UU4k-R4
