GET http://localhost:3001/MINKAN/api/chats/byUser/639f46cdac4c0a95095d623a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI2MzlmNDZjZGFjNGMwYTk1MDk1ZDYyM2EiLCJpYXQiOjE2NzE0MDk4NjUsImV4cCI6MTY3MTQxMzQ2NX0.PfYk2pyYECLnx_Xh-ysiaPdzi3oM4HH63BMwHkRZgOA